### ISSUE TITLE
Image not loading

### ISSUE THREAD

**Issue by morbatex** [mapintelligenceagency/landingpage#1]
**Describe the bug**
I think a picture of this man is not loading... Please fix
![index](https://user-images.githubusercontent.com/11612113/69917771-028b6480-146a-11ea-8bdc-5f85465a8a42.jpg)

**To Reproduce**
1. Go to 'https://mapintelligence.agency/'
2. Search for the picture
3. Fail to find it
4. Be sad

**Expected behavior**
The picture should be visible

**Comment by maxemann96** [comment]
Wontfix
